version = 1

[merge]
prioritize_ready_to_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"

[approve]
auto_approve_usernames = ["dependabot", "dependabot-preview", "gnarea"]
