name: Run CI and potentially release
on:
  pull_request:
  push:
    branches: [main]
jobs:
  static-checks:
    runs-on: ubuntu-latest
    name: static-checks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: root-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run static-checks

  ci:
    needs: static-checks
    strategy:
      matrix:
        node: [12, 14, 16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: "ci-nodejs${{ matrix.node }}-${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-nodejs${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run test:ci

  release:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: root-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build

      - name: Generate docs
        run: npm run doc-api

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
          allow_empty_commit: true
